### ISSUE TITLE
Website is missing / broken

### ISSUE THREAD

**Issue by b-long** [ManageIQ/manageiq_depot#19]
Attempted to open http://manageiq.org/depot and this page is returned :

![image](https://cloud.githubusercontent.com/assets/66993/22838478/507d4b9e-ef93-11e6-8f7b-ecbcc90129cd.png)

**Comment by carbonin** [comment]
Fairly sure the website is https://depot.manageiq.org/

That's what it says on the [README](https://github.com/ManageIQ/manageiq_depot#manageiq-community-depot)

**Comment by Fryguy** [comment]
It's wrong in the repo description... I'll update

**Comment by b-long** [comment]
Thanks @Fryguy , yes, I was looking at the repo description.  Sorry for all the noise.
